apiVersion: apps/v1
kind: Deployment
metadata:
  name: eros-iot-streams
  labels:
    app: eros
    type: backend
    deployment: eros-iot-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: eros-iot-streams
  template:
    metadata:
      labels:
        pod: eros-iot-streams
        app: eros
        type: backend
        deployment: eros-iot-streams
    spec:
      imagePullSecrets:
        - name: nemo-regcred
      containers:
        - name: eros-iot-streams
          image: nemometaos/eros-iot-streams
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DEBUG
              value: "1"
            - name: MINIO_DEFAULT_BUCKETS
              value: "iotdata"
            - name: MINIO_ENDPOINT
              value: "eros-minio:9000"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eros-minio-builtin-admin
                  key: password
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: eros-minio-builtin-admin
                  key: username
