include:
  - project: 'eclipsefdn/it/releng/gitlab-runner-service/gitlab-ci-templates'
    file: 'jobs/buildkit.gitlab-ci.yml'
  - project: 'eclipsefdn/it/releng/gitlab-runner-service/gitlab-ci-templates'
    file: 'pipeline-autodevops.gitlab-ci.yml'

stages:
  - build
  - test

build:data-catalogue:
  stage: build
  extends: .buildkit
  variables:
    CI_REGISTRY_IMAGE: "docker.io/nemometaos/data-catalogue"
    BUILD_CONTEXT: "data_catalogue"
    BUILD_CONTEXT_CHANGE: "data_catalogue"

build:data-pipeline:
  stage: build
  extends: .buildkit
  variables:
    CI_REGISTRY_IMAGE: "docker.io/nemometaos/data-pipeline"
    BUILD_CONTEXT: "data_pipeline"
    BUILD_CONTEXT_CHANGE: "data_pipeline"

build:iot_streams:
  stage: build
  extends: .buildkit
  variables:
    CI_REGISTRY_IMAGE: "docker.io/nemometaos/iot-streams"
    BUILD_CONTEXT: "iot_streams"
    BUILD_CONTEXT_CHANGE: "iot_streams"

build:training-environment:
  stage: build
  extends: .buildkit
  variables:
    CI_REGISTRY_IMAGE: "docker.io/nemometaos/training-environment"
    BUILD_CONTEXT: "training_environment"
    BUILD_CONTEXT_CHANGE: "training_environment"

unit-test:
  stage: test
  script:
    - echo "Running unit tests... This will take about 10 seconds."
    - sleep 10
    - echo "Tests passed succesfully!"
