{
 "title": "EMOTION",
 "time": { "from": "2025-08-19T06:10:27.308Z", "to": "2025-08-21T10:23:37.182Z" },
 "templating": {
  "list": [
   { "name": "vehicle", "label": "vehicle", "query": "SELECT vehicle FROM vehicle" }
  ]
 },
 "panels": [
  {
   "title": "Predicted battery percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage\nFROM \"vehicle_states\"\nWHERE\n  vehicle = $vehicle"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as \"forecast\"\nFROM predicted_battery_percentage_cat\nWHERE\n  vehicle = '$vehicle'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total km history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle1\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle2\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 2"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle3\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 3"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle4\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 4"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle5\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 5"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle6\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 6"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle7\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 7"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle8\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 8"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle9\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 9"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle10\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 10"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle11\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 11"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle12\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 12"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle13\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 13"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle14\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 14"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle15\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 15"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle16\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 16"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle17\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 17"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle18\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 18"
      }
     ]
    },
    {
     "title": "Charged kWh history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle1\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle2\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 2\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle3\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 3\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle4\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 4\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle5\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 5\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle6\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 6\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle7\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 7\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle8\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 8\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle9\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 9\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle10\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 10\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle11\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 11\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle12\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 12\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle13\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 13\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle14\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 14\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle15\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 15\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle16\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 16\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle17\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 17\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged as float) as vehicle18\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 18\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Amount of charges history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle1\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle2\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 2\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle3\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 3\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle4\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 4\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle5\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 5\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle6\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 6\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle7\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 7\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle8\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 8\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle9\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 9\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle10\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 10\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle11\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 11\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle12\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 12\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle13\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 13\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle14\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 14\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle15\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 15\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle16\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 16\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle17\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 17\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count as vehicle18\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 18\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Battery percentage history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle1\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle2\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 2\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle3\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 3\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle4\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 4\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle5\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 5\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle6\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 6\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle7\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 7\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle8\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 8\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle9\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 9\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle10\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 10\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle11\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 11\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle12\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 12\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle13\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 13\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle14\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 14\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle15\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 15\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle16\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 16\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle17\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 17\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage as vehicle18\nFROM \"vehicle_states\"\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle = 18\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Use-case",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individual vehicle km total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle1\nFROM \"vehicle_states\"\nWHERE\n  vehicle = $vehicle"
      }
     ]
    },
    {
     "title": "Individual vehicle kWh charged",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(kwh_charged AS float)\nFROM \"vehicle_states\"\nWHERE\n  vehicle = $vehicle"
      }
     ]
    },
    {
     "title": "Individual vehicle charge count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count\nFROM \"vehicle_states\"\nWHERE\n  vehicle = $vehicle"
      }
     ]
    },
    {
     "title": "Individual vehicle battery %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage\nFROM \"vehicle_states\"\nWHERE\n  vehicle = $vehicle"
      }
     ]
    },
    {
     "title": "Battery Pecentage for vehicle 1,3,8,9",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 3"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 8"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 9"
      }
     ]
    },
    {
     "title": "Km total for vehicle 1,2,3,4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle1\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle2\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 2"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle3\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 3"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot as vehicle4\nFROM \"vehicle_states\"\nWHERE\n  vehicle = 4"
      }
     ]
    }
   ]
  }
 ]
}