apiVersion: v1
kind: Service
metadata:
  name: eros-data-catalogue
  labels:
    app: eros
    type: frontend
    service: eros-data-catalogue
spec:
  selector:
    pod: eros-data-catalogue
    app: eros
    type: frontend
    deployment: eros-data-catalogue
  ports:
    - name: http
      port: 80
      targetPort: 8003
  type: ClusterIPdeployment.