apiVersion: v1
kind: Service
metadata:
  name: eros-keycloak
  labels:
    app: eros
    type: backend
    service: eros-keycloak
spec:
  selector:
    pod: eros-keycloak
    app: eros
    type: backend
    deployment: eros-keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP