apiVersion: v1
kind: Service
metadata:
  name: eros-grafana
  labels:
    app: eros
    type: frontend
    service: eros-grafana
spec:
  selector:
    pod: eros-grafana
    app: eros
    type: frontend
    deployment: eros-grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
