{
 "title": "EMOTION",
 "time": { "from": "2025-08-19T06:10:27.308Z", "to": "2025-08-21T10:23:37.182Z" },
 "templating": {
  "list": [
   {
    "name": "vehicle",
    "label": "vehicle",
    "query": "SELECT vehicle::bigint AS __value, vehicle::text AS __text\nFROM public.vehicle\nWHERE vehicle IS NOT NULL\nORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Predicted battery percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = ${vehicle}"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS \"forecast\"\nFROM predicted_battery_percentage_cat\nWHERE\n  vehicle::bigint = ${vehicle}\nORDER BY 1"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total km history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 2"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 3"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 4"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 5"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 6"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 7"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 8"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 9"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 10"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 11"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 12"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 13"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 14"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 15"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 16"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 17"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 18"
      }
     ]
    },
    {
     "title": "Charged kWh history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 2\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 3\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 4\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 5\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 6\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 7\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 8\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 9\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 10\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 11\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 12\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 13\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 14\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 15\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 16\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 17\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 18\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Amount of charges history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 2\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 3\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 4\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 5\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 6\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 7\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 8\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 9\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 10\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 11\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 12\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 13\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 14\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 15\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 16\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 17\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 18\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Battery percentage history across all vehicles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 2\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 3\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 4\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 5\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 6\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 7\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 8\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 9\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 10\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 11\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 12\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 13\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 14\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 15\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 16\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 17\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision AS value\nFROM public.vehicle_states\nWHERE\n  $__timeFilter(\"timestamp\")\nand vehicle::bigint = 18\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Use-case",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individual vehicle km total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = ${vehicle}"
      }
     ]
    },
    {
     "title": "Individual vehicle kWh charged",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  kwh_charged::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = ${vehicle}"
      }
     ]
    },
    {
     "title": "Individual vehicle charge count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  charges_count\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = ${vehicle}"
      }
     ]
    },
    {
     "title": "Individual vehicle battery %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = ${vehicle}"
      }
     ]
    },
    {
     "title": "Battery Pecentage for vehicle 1,3,8,9",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 3"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 8"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  battery_percentage::double precision\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 9"
      }
     ]
    },
    {
     "title": "Km total for vehicle 1,2,3,4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 1"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 2"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 3"
      },
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  km_tot::double precision AS value\nFROM public.vehicle_states\nWHERE\n  vehicle::bigint = 4"
      }
     ]
    }
   ]
  }
 ]
}